dist: bionic

language: go
go:
  - 1.19.x
env:
  global:
    - GO111MODULE=on
# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script:
  - go mod vendor
  - export GIT_VERSION=$(git describe --tags --long --always)
  - GOOS=linux GOARCH=amd64 go build -mod vendor -ldflags "-X main.version=${GIT_VERSION}" -o build/jenkins-node-state-exporter.linux-amd64 .
  - sha256sum build/jenkins-node-state-exporter.linux-amd64 > build/jenkins-node-state-exporter.linux-amd64.sha256sum

deploy:
  provider: releases
  api_key:
    secure: "g3gn/Rg9N1YR9a+uDCe/JEfun7tRDEPZBSQZxP1JsRN+7eUqgz+t1r/JaxE0JTK+kXSTvLuOsFZ0qll8pviE/VMFXobNeWUNRHh9Qa8jt7eyuiEVHTDZ0oOVrFrYd166aefBI6IJ1QMMKVMNKL+HTxkYdhXsZJrdtqwHDukOlzMXqe9ZO6FB+0P3aMazW+vcnAqUNjmZgk0E17IJl/TdUlIXiGh5kTIjUqpItRZL+xWIRf5oiZ+Ur7236nGVJd0XPllydPKKijAHiZcCXV8guzdxiSp47TwmBXSiRkMSck7oZvo1wplc2luzERSsRFxRiP+Tw/LXOgKm5PLw0zjJ+8It4bL8Ce4zKslU8CuujfYbl9XqD753wXC1rYrXNrFBsOr/KFCzwAGmLu2/Z7/bxZaBTbk6INQ84wzek0ajNnskgPJh1pJho0Iz0/+mMF2rAMdaaHKuOKbzVgDNfb0CvN5s38Uw+DBtqU+g7lkM7eR2fTJ1NjrMOnY5RrVoO7woQoB0csZyhBJ7yGMCQnB0ioXcNm1VFr/pBGcVGCUc8FMKDcTYCMTROUOSDizM+3hwpiSomFt1JQXB4/xsxWoLE3R6eyNUvtAJBO/btPR9FeJ4zB37uQMkWSoYbhi4KZzV6FeEjk/qRRG03uR6FyctEAnZLbWyecsWNtyDA5P712A="
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
